export const ACTION_LOAD_LIST_LIST = 'ACTION_LOAD_LIST_LIST';
export const ACTION_SET_SCREEN = 'ACTION_SET_SCREEN';
export const ACTION_LOAD_DATA = 'ACTION_LOAD_DATA';
export const ACTION_SET_SELECTION = 'ACTION_SET_SELECTION';
export const ACTION_ADD_WORD = 'ACTION_ADD_WORD';
export const ACTION_START_APPLICATION = 'ACTION_START_APPLICATION';
export const ACTION_SET_GLOBAL_VALUE = 'ACTION_SET_GLOBAL_VALUE';
